accelerate launch train_text_to_image_lora_sdxl.py ^
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" ^
  --pretrained_vae_model_name_or_path="madebyollin/sdxl-vae-fp16-fix" ^
  --dataset_name="MY DATASET" ^
  --validation_prompt="MY PROMPT" ^
  --num_validation_images=4 ^
  --validation_epochs=1 ^
  --output_dir="MY OUTPUT" ^
  --resolution=1024 ^
  --center_crop ^
  --random_flip ^
  --train_text_encoder ^
  --train_batch_size=1 ^
  --num_train_epochs=10 ^
  --checkpointing_steps=500 ^
  --gradient_accumulation_steps=4 ^
  --learning_rate=1e-04 ^
  --lr_warmup_steps=0 ^
  --report_to="wandb" ^
  --dataloader_num_workers=8 ^
  --allow_tf32 ^
  --mixed_precision="fp16" ^
  --push_to_hub ^
  --hub_model_id="MY MODEL NAME"
